source "https://api.berkshelf.com"

metadata

cookbook "cron", "~> 1.4.0"
cookbook "git", "~> 4.0.2"
cookbook "yum", "~> 3.0"
cookbook "yum-epel", "~> 0.3.6"
cookbook "yum-remi", "~> 0.1", git: 'git://github.com/njohns-pica9/yum-remi.git'
cookbook "php", "~> 1.4.6"
cookbook "redisio", "~> 1.7.1"
cookbook "python", "~> 1.4.6"
cookbook "lxmx_oh_my_zsh", "~> 0.5.0"
cookbook "composer", "~> 1.0.3"
