# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.auto_update = false
  end
  config.vm.hostname = "worker-berkshelf"
  config.omnibus.chef_version = :latest
  config.vm.box = "centos65"
  config.vm.network :private_network, type: "dhcp"

  config.berkshelf.enabled = true
  config.vm.provision :chef_solo do |chef|
  #  chef.json = {
  #    mysql: {
  #      server_root_password: 'rootpass',
  #      server_debian_password: 'debpass',
  #      server_repl_password: 'replpass'
  #    }
  #  }
  #
   chef.run_list = [
       "recipe[worker::default]"
   ]
  end

end
